all:
  stylesheets: [/sfDoctrineSimpleForumPlugin/css/default.css]
createTopicSuccess:
  javascripts: [/sfDoctrineSimpleForumPlugin/js/hint.js]
viewTopicSuccess:
  javascripts: [/sfDoctrineSimpleForumPlugin/js/jquery-1.3.2.min.js]
