sfDoctrineSimpleForumCategory:
  actAs: [Timestampable, SoftDelete, Sluggable]
  tableName: sf_doctrine_simple_forum_category
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    name: { type: string }
    stripped_name: { type: string }
    description: { type: string }
    rank: { type: integer } 
sfDoctrineSimpleForumForum:
  actAs: [Timestampable, SoftDelete, Sluggable]
  tableName: sf_doctrine_simple_forum_forum
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    name: { type: string }
    description: { type: string }
    rank: { type: integer }
    category_id: { type: integer(4) }
    nb_posts: { type: integer(4) }
    nb_topics: { type: integer(4) }
  relations:
    sfDoctrineSimpleForumCategory:
      alias: Category
      local: category_id
      foreign: id
      onDelete: cascade
sfDoctrineSimpleForumTopic:
  actAs: [Timestampable, SoftDelete,Sluggable]
  tableName: sf_doctrine_simple_forum_topic
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    title: { type: string(255) }
    is_sticked: { type: boolean, default: false }
    is_locked: { type: boolean, default: false }
    forum_id: { type: integer(4) }    
    user_id:       { type: integer }
    nb_posts:      { type: integer(4), default: 0 }
    nb_views:      { type: integer(10), default: 0 }
  relations:
    sfDoctrineSimpleForumForum:
      alias: Forum
      local: forum_id
      foreign: id
      onDelete: cascade
    sfDoctrineSimpleForumPost:
      alias: Posts
      type: many
      local: id
      foreign: topic_id
    sfGuardUser:
      alias: User
      local: user_id
      foreign: id
sfDoctrineSimpleForumPost:
  actAs: [Timestampable, SoftDelete]
  tableName: sf_doctrine_simple_forum_post
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    title: { type: string(255) }
    content: { type: string }
    topic_id: { type: integer(4) }
    is_reply_to_comment: { type: integer(1), default: 0 }
    reply_id: { type: integer(10) }
    user_id: { type: integer }
    first_post: { type: integer(1) }
    forum_id: { type: integer(4) }
  relations:
    sfDoctrineSimpleForumTopic:
      alias: Topic
      local: topic_id
      foreign: id
    sfGuardUser:
      alias: User
      local: user_id
      foreign: id
    sfDoctrineSimpleForumForum:
      alias: Forum
      local: forum_id
      foreign: id
      onDelete: cascade
sfDoctrineSimpleForumTopicView:
  actAs: [Timestampable, SoftDelete]
  tableName: sf_doctrine_simple_forum_topic_view
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    user_id: { type: integer }
    topic_id : {type: integer }
  relations:
    sfGuardUser:
      alias: User
      local: user_id
      foreign: id